/**
 * Coverage figures for the generated command surface.
 *
 * Every number here is transcribed from the committed Discovery index at
 * `src/discovery/manifest.json` (generated by `scripts/fetch-discovery.ts`),
 * which is what `grr api list` reads at runtime. Revisions are the
 * `discoveryRevision` each service document reported when it was last
 * refreshed, so a stale row here means the index moved, not that the docs
 * drifted.
 *
 * Every service has dedicated `grr <service>` commands — the tree is
 * generated from the index, so the fourteen namespaces are on equal footing
 * and `grr api` is the flat, id-based way into the same methods.
 */
export interface DiscoveryService {
  /** Key accepted by `grr api list --service` and the `grr api call` id prefix. */
  name: string;
  /** Human label used in prose. */
  label: string;
  /** Google API version this index was distilled from. */
  version: string;
  methods: number;
  /** Distinct scopes declared across the service's methods. */
  scopes: number;
  /** `revision` field of the Discovery document at refresh time. */
  revision: string;
  /** One-line note on what the service covers. */
  note: string;
}

export const discoveryServices: DiscoveryService[] = [
  {
    name: 'gmail',
    label: 'Gmail',
    version: 'v1',
    methods: 79,
    scopes: 14,
    revision: '20260921',
    note: 'Messages, threads, drafts, labels, history, filters, forwarding, send-as, and settings.',
  },
  {
    name: 'calendar',
    label: 'Calendar',
    version: 'v3',
    methods: 38,
    scopes: 17,
    revision: '20260826',
    note: 'Calendars, events, instances, ACL, free/busy, colors, and settings.',
  },
  {
    name: 'drive',
    label: 'Drive',
    version: 'v3',
    methods: 64,
    scopes: 10,
    revision: '20260923',
    note: 'Files, permissions, comments, revisions, changes, drives, and team drives.',
  },
  {
    name: 'people',
    label: 'People (Contacts)',
    version: 'v1',
    methods: 24,
    scopes: 12,
    revision: '20260923',
    note: 'Contacts, connections, other contacts, contact groups, and directory people.',
  },
  {
    name: 'chat',
    label: 'Chat',
    version: 'v1',
    methods: 54,
    scopes: 41,
    revision: '20260922',
    note: 'Spaces, messages, memberships, reactions, attachments, sections, and availability.',
  },
  {
    name: 'forms',
    label: 'Forms',
    version: 'v1',
    methods: 10,
    scopes: 6,
    revision: '20260922',
    note: 'Form bodies, responses, publish settings, and push-notification watches.',
  },
  {
    name: 'sheets',
    label: 'Sheets',
    version: 'v4',
    methods: 17,
    scopes: 5,
    revision: '20260921',
    note: 'Spreadsheet values, batch updates, data filters, and developer metadata.',
  },
  {
    name: 'tasks',
    label: 'Tasks',
    version: 'v1',
    methods: 14,
    scopes: 2,
    revision: '20260922',
    note: 'Task lists and the tasks inside them. See the scope caveat below.',
  },
  {
    name: 'slides',
    label: 'Slides',
    version: 'v1',
    methods: 5,
    scopes: 7,
    revision: '20260921',
    note: 'Presentation batch updates, page reads, and thumbnails.',
  },
  {
    name: 'docs',
    label: 'Docs',
    version: 'v1',
    methods: 3,
    scopes: 5,
    revision: '20260921',
    note: 'Document create, read, and batch update.',
  },
  {
    name: 'script',
    label: 'Apps Script',
    version: 'v1',
    methods: 16,
    scopes: 18,
    revision: '20260906',
    note: 'Script projects, deployments, versions, processes, and running functions.',
  },
  {
    name: 'analyticsadmin',
    label: 'Analytics Admin',
    version: 'v1beta',
    methods: 55,
    scopes: 2,
    revision: '20260923',
    note: 'Accounts, properties, data streams, custom dimensions and metrics, conversion events, and the Ads and Firebase links.',
  },
  {
    name: 'analyticsdata',
    label: 'Analytics Data',
    version: 'v1beta',
    methods: 11,
    scopes: 2,
    revision: '20260923',
    note: 'Run reports — standard, realtime, pivot, and batch — plus compatibility checks, metadata, and audience exports.',
  },
  {
    name: 'searchconsole',
    label: 'Search Console',
    version: 'v1',
    methods: 11,
    scopes: 2,
    revision: '20260923',
    note: 'Search analytics queries, sitemaps, sites, and URL inspection.',
  },
];

/** Sum of `methods` across every service. Matches `grr api list`'s own total. */
export const discoveryMethodTotal = discoveryServices.reduce(
  (total, service) => total + service.methods,
  0,
);
