[toolchain]
channel = "nightly"
components = ["clippy", "rustfmt", "rust-src", "rustc-dev", "llvm-tools-preview"]
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "aarch64-pc-windows-msvc",
]
profile = "minimal"

[rustfmt]
config = { tab_spaces = 4, hard_tabs = false, max_width = 100 }

