#!/usr/bin/env node
// Generate the per-service agent skills (skills/<service>/SKILL.md, one per
// service in the Discovery index) plus the skills index (skills/README.md)
// from the committed Discovery index (src/discovery/*.json).
//
// Why generate: agents should load the core skill (skills/grr/SKILL.md)
// first and pull in a per-service skill only when the task lands on that
// service — and every sentence of those per-service skills must come from
// the same index that compiles the CLI tree, so the skills can never drift
// from the binary. The daily discovery workflow regenerates them right
// after the command tree, so index, tree, and skills move in one PR.
//
// What is derived (never hand-written): the coverage map, method counts,
// the example commands and their flag spellings, the collision note, the
// least-privilege scope callout. What is templated: the section prose that
// restates the core skill's contract in service-specific form.
//
// Determinism: no wall-clock timestamps (the generated marker reuses the
// index manifest's own), and every sort is code-unit (`<`/`>`), never
// localeCompare — ICU collation differs across machines and would make
// `--check` flap between a dev box and CI.
//
// Usage:
//   node scripts/generate-skills.ts         # write skills/<svc>/SKILL.md ×N + skills/README.md
//   node scripts/generate-skills.ts --check # exit 1 if stale (CI gate)

import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import type { DistilledIndex, DistilledMethod, DistilledParameter, Manifest } from './discovery-index.ts';
import { flagId, kebab } from './script-utils.ts';

const ROOT = resolve(import.meta.dirname, '..');
const INDEX_DIR = resolve(ROOT, 'src', 'discovery');
const SKILLS_DIR = resolve(ROOT, 'skills');
const MANIFEST = resolve(INDEX_DIR, 'manifest.json');

const CHECK_ONLY = process.argv.includes('--check');

// The generated marker: provenance + the index's own timestamp, so it only
// moves when the index moves. pruneStaleSkills matches on the constant
// prefix to recognize files this script owns.
const MARKER = '<!-- GENERATED by scripts/generate-skills.ts from the committed Discovery index';
const markerLine = (generatedAt: string): string =>
  `${MARKER} — index generated at ${generatedAt}. Do not edit by hand; regenerate with \`npm run skills\`. -->`;

// Write verbs make better example commands than deletes; this uniform
// preference picks the friendliest write available in a resource group.
// Selection still flows from the index: if a method disappears upstream,
// the next candidate takes its place automatically.
const WRITE_LEAF_PREFERENCE = [
  'send', 'insert', 'create', 'append', 'add', 'submit', 'update', 'patch',
  'quickAdd', 'move', 'copy', 'import', 'clear', 'runReport', 'batchUpdate',
  'batchDelete', 'batchModify', 'trash', 'untrash', 'delete',
];

// Services at or above this method count get a fourth example from a
// resource group outside the flagship, so big branches show breadth.
const BREADTH_EXAMPLE_THRESHOLD = 40;

function assert(condition: unknown, message: string): void {
  if (!condition) {
    console.error(`generate-skills: ${message}`);
    process.exit(1);
  }
}

/** Code-unit comparison — locale-independent, so output is stable everywhere. */
function cmp(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

/**
 * The narrowest scope a method accepts — mirrors
 * `Method::least_privilege_scope` in src/discovery.rs exactly: the last
 * `googleapis.com/auth/...` entry (Discovery lists scopes in descending
 * breadth), falling back to the first scope overall.
 */
function leastPrivilegeScope(method: DistilledMethod): string | null {
  for (let i = method.scopes.length - 1; i >= 0; i--) {
    if (method.scopes[i].startsWith('https://www.googleapis.com/auth/')) return method.scopes[i];
  }
  return method.scopes[0] ?? null;
}

const leafName = (id: string): string => id.split('.').pop() ?? '';
const resourcePath = (id: string): string => id.split('.').slice(0, -1).join('.');
const topSegment = (id: string): string => id.split('.')[0] ?? '';

/** A parameter collides when its literal name is a reserved flag id. */
const collisionParam = (method: DistilledMethod): DistilledParameter | null =>
  method.parameters.find((p) => p.name === 'format' || p.name === 'query') ?? null;

// ———————————————————————————— Load the index ————————————————————————————

async function loadIndex(): Promise<DistilledIndex[]> {
  // The manifest decides WHICH services exist — deriving the list here
  // keeps the generator from silently drifting behind fetch-discovery.ts.
  const manifest = JSON.parse(await readFile(MANIFEST, 'utf8')) as Manifest;
  const serviceNames = Object.keys(manifest.services ?? {}).sort(cmp);
  assert(serviceNames.length > 0, 'manifest lists no services; run fetch-discovery.ts first');

  const services: DistilledIndex[] = [];
  for (const name of serviceNames) {
    const index = JSON.parse(await readFile(resolve(INDEX_DIR, `${name}.json`), 'utf8')) as DistilledIndex;
    assert(index.name === name, `${name}.json claims to be ${index.name}`);
    assert(Array.isArray(index.methods) && index.methods.length > 0, `${name}.json has no methods`);
    // The skills quote the manifest counts; they must match the real files.
    assert(
      manifest.services[name].methods === index.methods.length,
      `${name}: manifest says ${manifest.services[name].methods} methods, file has ${index.methods.length}`,
    );
    const seen = new Set<string>();
    for (const method of index.methods) {
      assert(!seen.has(method.id), `${name}: duplicate method id ${method.id}`);
      seen.add(method.id);
      assert(method.httpMethod && method.path !== undefined, `${name}: malformed method ${method.id}`);
    }
    services.push(index);
  }
  return services;
}

// ———————————————————————————— Service analysis ————————————————————————————

interface Group {
  path: string;
  methods: DistilledMethod[];
}

interface Analysis {
  service: DistilledIndex;
  groups: Group[];          // every resource path, each method counted once
  flagship: Group;           // the largest resource group
  collisions: DistilledMethod[];
  readOnlyScope: { scope: string; methods: number } | null;
}

function analyze(service: DistilledIndex): Analysis {
  const byPath = new Map<string, DistilledMethod[]>();
  for (const method of service.methods) {
    const path = resourcePath(method.id);
    const bucket = byPath.get(path) ?? [];
    bucket.push(method);
    byPath.set(path, bucket);
  }
  const groups: Group[] = [...byPath.entries()]
    .map(([path, methods]) => ({ path, methods }))
    .sort((a, b) => b.methods.length - a.methods.length || cmp(a.path, b.path));

  const collisions = service.methods
    .filter((m) => collisionParam(m) !== null)
    .sort((a, b) => cmp(a.id, b.id));

  // Service-level scope callout: prefer scopes that end in `.readonly` and
  // are the least-privilege scope of the most methods — the narrowest
  // consent that covers the service's read paths. Without any readonly
  // scope, fall back to the most common least-privilege scope.
  const freq = new Map<string, number>();
  for (const method of service.methods) {
    const scope = leastPrivilegeScope(method);
    if (scope) freq.set(scope, (freq.get(scope) ?? 0) + 1);
  }
  const ranked = [...freq.entries()]
    .map(([scope, methods]) => ({ scope, methods }))
    .sort((a, b) => b.methods - a.methods || cmp(a.scope, b.scope));
  const readOnlyScope =
    ranked.find((r) => r.scope.endsWith('.readonly')) ?? ranked[0] ?? null;

  return { service, groups, flagship: groups[0] ?? { path: '', methods: [] }, collisions, readOnlyScope };
}

// ———————————————————————————— Example rendering ————————————————————————————

interface Example {
  method: DistilledMethod;
  flags: string[];
}

/** The flag spelling + sample value for one parameter. */
function flagArg(param: DistilledParameter): string {
  const id = flagId(param.name);
  if (param.type === 'boolean' && !param.repeated) return `--${id}`;
  if (Array.isArray(param.enum) && param.enum.length > 0) {
    return `--${id} ${String(param.enum[0])}`;
  }
  if (param.type === 'integer') return `--${id} ${param.required ? '1' : '10'}`;
  if (param.name === 'userId') return `--${id} me`; // the documented special value
  return `--${id} <${kebab(param.name)}>`;
}

/**
 * Required flags in Discovery's own order — the `required` array lists
 * path parameters in URL order (`userId` before `id`), which is also the
 * natural reading order for the command line.
 */
function requiredFlags(method: DistilledMethod): string[] {
  const byName = new Map(method.parameters.map((p) => [p.name, p]));
  const flags: string[] = [];
  for (const name of method.required) {
    const param = byName.get(name);
    if (param) flags.push(flagArg(param));
  }
  for (const param of method.parameters) {
    if (param.required && !method.required.includes(param.name)) flags.push(flagArg(param));
  }
  return flags;
}

/** One optional integer flag on a list call shows the typed-flag rule. */
function pageSizeFlavor(method: DistilledMethod): string[] {
  const param = method.parameters.find((p) => !p.required && p.type === 'integer' && !p.repeated);
  return param ? [flagArg(param)] : [];
}

/** The renamed collision flag (e.g. `--param-format minimal`) when optional. */
function collisionFlavor(method: DistilledMethod): string[] {
  const param = collisionParam(method);
  if (!param || param.required) return [];
  return [flagArg(param)];
}

function renderExample(service: string, example: Example): string {
  const segments = example.method.id.split('.');
  return ['grr', service, ...segments, ...example.flags].join(' ');
}

// ———————————————————————————— Example selection ————————————————————————————

/**
 * Deterministic tiers, flagship resource first, code-unit order everywhere:
 *   1. a `list` (flagship group, then flagship's top-level branch, then
 *      anywhere) — reads with required flags + a page-size flavor;
 *   2. a `get` (same scoping) — path params; carries the collision flag
 *      when the method has a `format`/`query` parameter;
 *   3. a `list` breadth example for big services, from a resource outside
 *      the flagship's top segment;
 *   4. the first collision method (`--param-query`/`--param-format`) if no
 *      example shows one yet;
 *   5. the friendliest write by verb preference, always with `--dry-run`;
 *   6. fillers (reads then writes) until at least three examples exist.
 */
function pickExamples(a: Analysis): Example[] {
  const { service, flagship } = a;
  const top = topSegment(flagship.methods[0]?.id ?? '');
  const byId = (x: DistilledMethod, y: DistilledMethod) => cmp(x.id, y.id);
  const isGet = (m: DistilledMethod) => m.httpMethod === 'GET';

  const findRead = (verb: string, scope: 'flagship' | 'branch' | 'any'): DistilledMethod | null => {
    let pool: DistilledMethod[];
    if (scope === 'flagship') pool = flagship.methods;
    else if (scope === 'branch') pool = service.methods.filter((m) => topSegment(m.id) === top);
    else pool = service.methods;
    const hits = pool.filter((m) => isGet(m) && leafName(m.id) === verb).sort(byId);
    return hits[0] ?? null;
  };

  const findWrite = (scope: DistilledMethod[]): DistilledMethod | null => {
    const writes = scope.filter((m) => !isGet(m)).sort(byId);
    for (const pref of WRITE_LEAF_PREFERENCE) {
      const hit = writes.find((m) => leafName(m.id).startsWith(pref));
      if (hit) return hit;
    }
    return writes[0] ?? null;
  };

  const reads: Example[] = [];
  const used = new Set<string>();
  const take = (method: DistilledMethod | null, flags: string[]): boolean => {
    if (!method || used.has(method.id)) return false;
    used.add(method.id);
    reads.push({ method, flags });
    return true;
  };

  const list = findRead('list', 'flagship') ?? findRead('list', 'branch') ?? findRead('list', 'any');
  if (list) take(list, [...requiredFlags(list), ...pageSizeFlavor(list)]);

  const get = findRead('get', 'flagship') ?? findRead('get', 'branch') ?? findRead('get', 'any');
  if (get) take(get, [...requiredFlags(get), ...collisionFlavor(get)]);

  // Breadth: a list outside the flagship's top segment, else any unused list.
  if (service.methods.length >= BREADTH_EXAMPLE_THRESHOLD) {
    const outside = service.methods
      .filter((m) => isGet(m) && leafName(m.id) === 'list' && topSegment(m.id) !== top)
      .sort(byId)
      .find((m) => !used.has(m.id));
    const breadth = outside
      ?? service.methods
        .filter((m) => isGet(m) && leafName(m.id) === 'list')
        .sort(byId)
        .find((m) => !used.has(m.id))
      ?? service.methods.filter((m) => isGet(m)).sort(byId).find((m) => !used.has(m.id))
      ?? null;
    if (breadth) take(breadth, [...requiredFlags(breadth), ...pageSizeFlavor(breadth)]);
  }

  // The collision rule, shown once, on a method that actually needs it.
  if (a.collisions.length > 0 && !reads.some((e) => collisionParam(e.method))) {
    const hit = a.collisions.find((m) => !used.has(m.id));
    if (hit) take(hit, [...requiredFlags(hit), ...collisionFlavor(hit)]);
  }

  const write = findWrite(flagship.methods) ?? findWrite(service.methods);
  const writes: Example[] = [];
  if (write && !used.has(write.id)) {
    used.add(write.id);
    writes.push({ method: write, flags: [...requiredFlags(write), '--dry-run'] });
  }

  // Fill to the three-example minimum: unused reads first (shallowest
  // resource path wins — `spreadsheets.get` before `developerMetadata.get`),
  // then writes.
  const byDepth = (x: DistilledMethod, y: DistilledMethod) =>
    x.id.split('.').length - y.id.split('.').length || cmp(x.id, y.id);
  for (const method of service.methods.filter(isGet).sort(byDepth)) {
    if (reads.length + writes.length >= 3) break;
    if (!used.has(method.id)) take(method, [...requiredFlags(method), ...pageSizeFlavor(method)]);
  }
  for (const method of service.methods.sort(byId)) {
    if (reads.length + writes.length >= 3) break;
    if (used.has(method.id) || isGet(method)) continue;
    used.add(method.id);
    writes.push({ method, flags: [...requiredFlags(method), '--dry-run'] });
  }

  return [...reads, ...writes];
}

// ———————————————————————————— Markdown emission ————————————————————————————

/** Human-facing service word: "Gmail API" -> "Gmail". */
const shortTitle = (title: string): string => title.replace(/\s+API$/, '');

/**
 * The load-trigger summary: resource names only, biggest subtrees first.
 * Single-top services (gmail: everything under `users`) name the level-2
 * branches; multi-top services name the top-level groups.
 */
function groupSummary(a: Analysis): string {
  const { service } = a;
  const topPaths = [...new Set(service.methods.map((m) => topSegment(m.id)))].sort(cmp);
  const sizes = new Map<string, number>();
  for (const method of service.methods) {
    const segments = method.id.split('.');
    const child = topPaths.length === 1 && segments.length >= 2 ? segments[1] : segments[0];
    sizes.set(child, (sizes.get(child) ?? 0) + 1);
  }
  const names = [...sizes.entries()]
    .sort((x, y) => y[1] - x[1] || cmp(x[0], y[0]))
    .map(([name]) => name);
  const top5 = names.slice(0, 5).join(', ');
  return top5 + (names.length > 5 ? ', …' : '');
}

function frontmatterDescription(a: Analysis): string {
  const { service } = a;
  const svc = service.name;
  const title = shortTitle(service.title);
  return (
    `Use when the task touches ${title} through grr (${service.methods.length} methods under ` +
    `\`grr ${svc}\` — ${groupSummary(a)}). Carries the service's generated command map, ` +
    `the naming rule applied to ${svc}, example commands verified with --dry-run, and the ` +
    `least-privilege scope callout.`
  );
}

function coverageTable(a: Analysis): string {
  const rows = a.groups
    .map((g) => `| \`${g.path}\` | ${g.methods.length} |`)
    .join('\n');
  const total = a.groups.reduce((sum, g) => sum + g.methods.length, 0);
  assert(total === a.service.methods.length, `${a.service.name}: coverage table counts ${total} != ${a.service.methods.length}`);
  return `| Resource path (the id prefix — each command walks these words) | Methods |\n| --- | --- |\n${rows}`;
}

function namingSection(a: Analysis, namingExample: DistilledMethod): string[] {
  const svc = a.service.name;
  const lines = [
    `- Id dots become spaces: \`${svc}.${namingExample.id}\` → \`grr ${svc} ${namingExample.id.replaceAll('.', ' ')}\`. Resource segments and method names keep their exact Discovery casing (\`otherContacts\`, \`getProfile\`).`,
    `- Flags are the same ids, camelCase → kebab-case: \`userId\` → \`--user-id\`, \`maxResults\` → \`--max-results\`. Integers parse as numbers, booleans are presence flags, repeated parameters repeat, enum parameters validate.`,
  ];
  if (a.collisions.length > 0) {
    const spellings = [...new Set(a.collisions.flatMap((m) => m.parameters
      .filter((p) => p.name === 'format' || p.name === 'query')
      .map((p) => `\`--${flagId(p.name)}\``)))]
      .sort(cmp)
      .join(' or ');
    lines.push(
      `- ${a.collisions.length} method${a.collisions.length === 1 ? '' : 's'} here take${a.collisions.length === 1 ? 's' : ''} a parameter literally named ` +
        `\`format\` or \`query\`; that flag is spelled ${spellings} so it cannot collide with the reserved leaf flags.`,
    );
  } else {
    lines.push('- No parameter in this service collides with the reserved flag names (`params`, `body-file`, `query`, `dry-run`, `format`).');
  }
  lines.push(
    '- Request bodies are untyped by design: `--params \'<json>\'` or `--body-file PATH|-`. Typed flags win on conflict.',
  );
  const top = topSegment(namingExample.id);
  if (top === svc) {
    lines.push(
      `- Yes, the word doubles in commands like \`grr ${svc} ${top} …\`: the service is \`${svc}\` and the top resource id is also \`${top}\`.`,
    );
  }
  return lines;
}

function scopesSection(a: Analysis): string[] {
  const { service, readOnlyScope } = a;
  const lines: string[] = [];
  if (readOnlyScope) {
    const fraction = `${readOnlyScope.methods} of ${service.methods.length} methods`;
    lines.push(
      `- Least privilege for reads: \`${readOnlyScope.scope}\` — the narrowest scope the service's methods accept (it is the least-privilege scope for ${fraction}). Per method, ask the index: \`grr api describe <id>\` → \`leastPrivilegeScope\`.`,
    );
  }
  lines.push(
    '- Scope honesty: the build consents to every scope the embedded index names, so any method in the index is inside the grant. A `403` is therefore not a missing consent: it is either a grant that predates the current scope set (the remedy is a human re-running `grr auth login`) or an API that is not enabled on the Cloud project. Surface that distinction; never retry a 403 in a loop.',
  );
  return lines;
}

function skillMarkdown(a: Analysis, generatedAt: string): string {
  const { service } = a;
  const svc = service.name;
  const examples = pickExamples(a);
  assert(examples.length >= 3, `${svc}: only ${examples.length} examples selected`);
  const exampleLines = examples.map((e) => renderExample(svc, e)).join('\n');
  const revision = service.revision ? `, Discovery revision ${service.revision}` : '';

  const body = [
    `# grr ${svc} — ${service.title}`,
    '',
    `**${service.methods.length} methods**, ${service.version}${revision}, all reached as \`grr ${svc} <resource…> <method>\` and generated from the same committed index as the CLI tree — this file, \`grr api\`, and \`grr ${svc} --help\` never disagree. Load the core skill first: [grr](../grr/SKILL.md) owns the discovery discipline, the output contract, the safety flags, multi-account, \`mcp\`, and \`ask\`.`,
    '',
    '## Coverage',
    '',
    coverageTable(a),
    '',
    `## Naming, applied to ${svc}`,
    '',
    ...namingSection(a, examples[0].method),
    '',
    '## Examples',
    '',
    '```sh',
    exampleLines,
    '```',
    '',
    'Values in `<angle brackets>` are placeholders — substitute real ids (`me` is the authenticated user wherever the parameter is `--user-id`). Append `--dry-run` to any example to print the resolved request — verb, URL, scopes — instead of sending it.',
    '',
    '## Scopes',
    '',
    ...scopesSection(a),
    '',
    '## Contract',
    '',
    '- stdout is data, stderr is logs; JSON by default, `-f jsonl|table|pretty` to switch.',
    '- `--dry-run` before anything destructive — the resolved request as JSON, nothing sent.',
    '- Non-zero exit on failure; errors are actionable (a 403 names the missing scope, a typo gets ranked suggestions).',
    '',
    '## Go deeper',
    '',
    '- Core skill: [skills/grr/SKILL.md](../grr/SKILL.md) — discipline, contract, safety, accounts.',
    `- \`grr api describe ${svc}.${examples[0].method.id}\` — the authority on one method's parameters and scopes.`,
    `- \`grr api list --service ${svc}\` and \`grr ${svc} --help\` — browse the whole branch, offline, before any login.`,
    `- Site reference: [grr-cli.pages.dev/docs/api-reference/${svc}/](https://grr-cli.pages.dev/docs/api-reference/${svc}/)`,
    '',
  ].join('\n');

  return [
    '---',
    `name: grr-${svc}`,
    `description: "${frontmatterDescription(a)}"`,
    '---',
    '',
    markerLine(generatedAt),
    '',
    body,
    '',
  ].join('\n');
}

function readmeMarkdown(services: Analysis[], generatedAt: string): string {
  const core = '- **[grr](./grr/SKILL.md)** — the core skill: the discover-first discipline (`grr schema` → `grr api list` → `grr api describe` → `--dry-run`), the method-id naming rule, the output contract, safety flags, and multi-account. Load this one first.';
  const rows = services
    .map((a) => `- **[grr-${a.service.name}](./${a.service.name}/SKILL.md)** — ${frontmatterDescription(a)}`)
    .join('\n');
  return [
    '# grr agent skills',
    '',
    'Agent skills for driving [grr](../README.md), the Rust CLI for Google Workspace. One core skill plus one skill per service, every service skill generated from the committed Discovery index (`src/discovery/*.json`) by `node scripts/generate-skills.ts` (`npm run skills`) — the skills, the command tree, and `grr api` all read the same source, so they can never drift.',
    '',
    '## Progressive loading',
    '',
    '1. **Load the core skill first** — it teaches the moves that work for every service.',
    '2. **Pull a service skill on demand** — when the task settles on Gmail, Calendar, Drive, or any of the 14 services, load that service\'s skill for its command map, verified examples, and scope callout.',
    '',
    '## Install',
    '',
    '### With grr (offline)',
    '',
    '```sh',
    'grr skills install            # all 16 into ~/.agents/skills/ — the cross-client user-level location',
    'grr skills install --claude   # mirror into ~/.claude/skills/ too (Claude Code reads only that)',
    'grr skills install --force    # replace files that differ from the packaged copy',
    'grr skills list               # the packaged set, and what each target directory holds',
    '```',
    '',
    'The skill files are compiled into the `grr` binary, so install needs no network: writing an identical file is a no-op, and a locally edited file is left alone (with a non-zero exit) unless `--force` is passed.',
    '',
    '### With the skills CLI',
    '',
    '```sh',
    'npx skills add https://github.com/debanjanbasu/grr-cli                          # the whole skills directory (core + services)',
    'npx skills add https://github.com/debanjanbasu/grr-cli/tree/main/skills/gmail   # one service skill',
    '```',
    '',
    '## The skills',
    '',
    core,
    rows,
    '',
    markerLine(generatedAt),
    '',
  ].join('\n');
}

// ———————————————————————————— Write / check ————————————————————————————

/** Remove generated skill directories for services the index no longer
 * lists. Only directories containing a file with our marker are touched. */
async function pruneStaleSkills(validServices: Set<string>, dryRun: boolean): Promise<string[]> {
  const removed: string[] = [];
  const entries = await readdir(SKILLS_DIR, { withFileTypes: true }).catch(() => []);
  for (const entry of entries) {
    if (!entry.isDirectory() || validServices.has(entry.name) || entry.name === 'grr') continue;
    const file = resolve(SKILLS_DIR, entry.name, 'SKILL.md');
    const content = await readFile(file, 'utf8').catch(() => null);
    if (content === null || !content.includes(MARKER)) continue; // never touch foreign files
    if (!dryRun) await rm(resolve(SKILLS_DIR, entry.name), { recursive: true });
    removed.push(entry.name);
  }
  return removed;
}

const relPath = (path: string): string => path.slice(ROOT.length + 1).replaceAll('\\', '/');

async function main(): Promise<void> {
  const manifest = JSON.parse(await readFile(MANIFEST, 'utf8')) as Manifest;
  const services = await loadIndex();
  const analyses = services.map(analyze);
  const totalMethods = analyses.reduce((sum, a) => sum + a.service.methods.length, 0);

  const targets: Array<{ path: string; content: string }> = [];
  for (const a of analyses) {
    targets.push({
      path: resolve(SKILLS_DIR, a.service.name, 'SKILL.md'),
      content: skillMarkdown(a, manifest.generatedAt),
    });
  }
  targets.push({ path: resolve(SKILLS_DIR, 'README.md'), content: readmeMarkdown(analyses, manifest.generatedAt) });

  if (CHECK_ONLY) {
    const stale: string[] = [];
    for (const target of targets) {
      // Line-ending-independent compare: Windows runners check out with
      // CRLF (autocrlf) while the generator writes LF — see the matching
      // note in generate-commands.ts.
      const previous = (await readFile(target.path, 'utf8').catch(() => null))?.replace(/\r\n/g, '\n') ?? null;
      if (previous !== target.content) stale.push(relPath(target.path));
    }
    const phantom = await pruneStaleSkills(new Set(analyses.map((a) => a.service.name)), true);
    if (stale.length > 0 || phantom.length > 0) {
      if (phantom.length > 0) console.error(`Stale skill directories to remove: ${phantom.map((n) => `skills/${n}/`).join(', ')}`);
      if (stale.length > 0) {
        console.error('\nGenerated skills are stale:');
        for (const path of stale) console.error(`  ${path}`);
        console.error('\nRun: node scripts/generate-skills.ts');
      }
      process.exit(1);
    }
    console.log(
      `generated skills current: ${analyses.length} services, ${totalMethods} methods, ` +
        `${analyses.reduce((sum, a) => sum + pickExamples(a).length, 0)} examples`,
    );
    return;
  }

  let written = 0;
  for (const target of targets) {
    const previous = await readFile(target.path, 'utf8').catch(() => null);
    if (previous === target.content) continue;
    await mkdir(dirname(target.path), { recursive: true });
    await writeFile(target.path, target.content, 'utf8');
    written++;
    console.log(`wrote ${relPath(target.path)}`);
  }
  const removed = await pruneStaleSkills(new Set(analyses.map((a) => a.service.name)), false);
  for (const name of removed) console.log(`removed stale skills/${name}/`);

  console.log(
    `${analyses.length} services, ${totalMethods} methods, ` +
      `${targets.length - written} files unchanged, ${written} written` +
      (removed.length > 0 ? `, ${removed.length} removed` : ''),
  );
  const examples = analyses.reduce((sum, a) => sum + pickExamples(a).length, 0);
  console.log(`${examples} example commands derived for the ${analyses.length} service skills`);
}

main().catch((error: unknown) => {
  console.error(`generate-skills failed: ${error instanceof Error ? error.stack : String(error)}`);
  process.exit(1);
});
